# flourish_ai/sub_agents/critic/agent.py

from google.adk.agents import LlmAgent
from . import prompt

#A strong judgment and reasoning required for quality control
MODEL = "gemini-2.0-flash" 

critic_agent = LlmAgent(
    model=MODEL,
    name="Flourish_Pedagogical_Critic",
    instruction=prompt.CRITIC_AGENT_PROMPT,
    output_key=prompt.CRITIC_OUTPUT_KEY,
    description="Critiques generated lesson plans for pedagogical soundness, safety, and accessibility.",
    # No tools needed; its input is the content generated by the Curriculum Agent.
    tools=[] 
)